@startuml US006_SSD
'https://plantuml.com/sequence-diagram
autonumber

actor "DGS" as DGS
activate DGS
DGS -> System : asks to see number of people vaccinated
activate System
System --> DGS : exports file with people vaccinated in each center

deactivate System
deactivate DGS

@enduml