@startuml
autonumber
actor "Administrator" as OE

activate OE
OE -> ":System" : Starts to register a new Employee
activate ":System"
":System" --> OE : requests data (name,address,phoneNumber,emailAddress)
deactivate ":System"

OE -> ":System" : types requested data
activate ":System"
":System" --> OE : shows all data and requests confirmation
deactivate ":System"

OE -> ":System" : confirms the data
activate ":System"
":System" --> OE : informs operation success
deactivate ":System"

deactivate OE

@enduml