@startuml
'https://plantuml.com/use-case-diagram
left to right direction
:Administrator: as Admin
:Nurse:
:Receptionists:
:SNS User: as User
:Center Coordinator: as CC


Admin -- (UC1 - Register Center)
Admin -- (UC2 - Register User)
Admin -- (UC3 - Register Center Coordinator)
Admin -- (UC4 - Register Receptionist)
Admin -- (UC5 - Register Nurse)

Receptionists -- (UC6 - Register arrival of User)
Receptionists -- (UC7 - Acknowledge system that the user\n is ready for vaccination)

Nurse -- (UC8 - Issue and Deliver vaccination certificate)
Nurse -- (UC9 - Check list of Users present for vaccination)
Nurse -- (UC10 - Check Users Info and health conditions)
Nurse -- (UC11 - Register vaccination event)


User -- (UC12 - Request Vaccination Certificate)
User -- (UC13 - Schedule vaccination)
User -- (UC14 - Authorize DGS to send SMS)


CC -- (UC15 - Manage Covid-19 Process)
CC -- (UC16 - Monitor vaccination process)


@enduml